### ISSUE TITLE
Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'ColorThief.Forms, Version=1.1.0.1, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile? File name: 'ColorThief.Forms.dll'

### ISSUE THREAD

**Issue by AmirHossein484** [KSemenenko/ColorThief#10]
Hi, I get this error in Xamarin.Forms 3 .net Standard 2 project, What should I do?

Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'ColorThief.Forms, Version=1.1.0.1, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'ColorThief.Forms.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	ColorThiefDemo.Android

**Comment by KSemenenko** [comment]
Hi, I will check

**Comment by AmirHossein484** [comment]
Thank, I'll be waiting

**Comment by AmirHossein484** [comment]
Hi, Sorry, Do you think that it takes too long to do this?

**Comment by KSemenenko** [comment]
in general, I need to update the project so that it uses the .net standard

**Comment by KSemenenko** [comment]
@AmirHossein484  well, or you can just use my code in your project. it will be faster.
